[package]
name = "euclider"
version = "0.1.0"
authors = ["Jakub HlusiÄka <jakub.hlusicka@email.cz>"]

[dependencies]
glium = "0.*"
nalgebra = "0.*"
image = "0.*"
scoped_threadpool = "0.*"
noise = "0.*"
rand = "0.*"
palette = "0.*"
