[package]
name = "euclider"
version = "0.11.2"
authors = ["Jakub HlusiÄka <jakub.hlusicka@email.cz>"]

[dependencies]
clippy = "0.*"
glium = "0.*"
nalgebra = "0.*"
image = "0.*"
scoped_threadpool = "0.*"
noise = "0.*"
rand = "0.*"
num = "0.*"
palette = "0.*"
json = "0.*"
parse-generics-shim = "0.*"
mopa = { git = "https://github.com/Limeth/mopa.git" }
clap = "2.*"
meval = "0.*"
